stages:
  - build

build linux clang format:
  stage: build
  image: docker
  services: 
    - docker:dind
  script: 
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - cd linux-clang-format
    - docker build -f Dockerfile -t ${CI_REGISTRY_IMAGE}:clangformat .
    - docker push ${CI_REGISTRY_IMAGE}:clangformat


build linux x64:
  stage: build
  image: docker
  services: 
    - docker:dind
  script: 
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - cd linux
    - docker build -f Dockerfile -t ${CI_REGISTRY_IMAGE}:linux-x64 .
    - docker push ${CI_REGISTRY_IMAGE}:linux-x64

build android x64:
  stage: build
  image: docker
  services: 
    - docker:dind
  script:
    - cd android
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -f Dockerfile -t ${CI_REGISTRY_IMAGE}:android-x64 .
    - docker push ${CI_REGISTRY_IMAGE}:android-x64

build windows x64:
  stage: build
  image: docker
  services: 
    - docker:dind
  script: 
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - cd windows
    - docker build -f Dockerfile -t ${CI_REGISTRY_IMAGE}:windows-x64 .
    - docker push ${CI_REGISTRY_IMAGE}:windows-x64
